language: android
jdk: oraclejdk8
dist: trusty

env:
  global:
    - ANDROID_API_LEVEL=30
    - ANDROID_BUILD_TOOLS_VERSION=30.0.0
    - ANDROID_EMU_API_LEVEL=22
    - ANDROID_ABI=armeabi-v7a
    - QEMU_AUDIO_DRV=none

android:
  components:
    # Android SDK Tools
    - tools
    - platform-tools
    
    # BuildTools version
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    
    # APIs 
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMU_API_LEVEL
    
    # Additional components (repos to fetch lisences)
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    
    # emulator instance 
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL

  licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-$ANDROID_EMU_API_LEVEL"
  - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL"

before_script:
  - chmod +x gradlew
  
  # Emulator instance 
  - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google_apis/$ANDROID_ABI
  - emulator -avd test -no-window & 
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

#script:
#  - ./gradlew clean build
#  - ./gradlew test
